### ISSUE TITLE
Trouble creating rooms using my firebase console account

### ISSUE THREAD

**Issue by bluecode-0** [john-safwat/Chat#46]
**Describe the bug**
I've tried your app with my custom 'firebase_options.dart' but I can't create rooms anymore, (on my account).
Possible, maybe I have't enabled all necesary services.

**Comment by john-safwat** [comment]
firebase_options.dart is not enough to change the firebase connection there is some other files must be changed 
also You can try to create new project and copy all files in lib folder except my firebase options , the assets and the pubspec.yaml  and configure with your firebase project it may work 
i hope this helps
